---
title: "SOS2900"
subtitle: "Seminar 1: Introduction to R and prediction"
author: "Torkild H. Lyngstad"
date: "18 januar 2018"
output: 
  beamer_presentation: 
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# What is R?
- R is a statistical programming language
    - Statistical analysis
    - Data visualization
    - Data mining
    - General programming

- It is open-source
    - Free as in “free beer” and “free speech”
    - Large active community around R
    - Many contributed packages


# Why do you need to know R?

- R is very powerful, and allows us to manually compute
everything we want if we choose to
- For many of the methods we use, R has either the simplest or
the only implementation.
- A main tool among Data scientists

# What do you need to know about R?
- In this course not much. We intend the methods we will
describe to be usable by researchers with little experience in R

- Tiny bits of programming
- Cookbook method

- But it is strongly advised that you learn more about R if you
want to do more in data science.

- First use of R and RStudio
- We will use the environment RStudio for our work in R

- What is the difference?
    - R is the program interpreter. Does the job.
    - RStudio is a "front end" that makes it easier to use R.

# Meet RStudio!

- RStudio has 4 panels:

Console: This is the actual R window, you can enter commands here and execute them by pressing enter
Source: This is where we can edit scripts. It is where you do most of your work Control-enter sends selected codes to the console
Plots/Help: This is where plots and help pages will be shown
Workspace: Shows which objects you currently have
    - Anything following a # symbol is treated as a comment!## R Markdown

# R as calculator

- You can use R as a calculator

![(materials/seminar-1-r-calculator1.png)


# In R, everything has a name

- Assign and use objects
    - The <- operator can be used to store values into objects
    - An object can contain anything in R
    - R expressions that are not stored in an object are printed

- Object names are...
    - Unique: If you use the same name, the old will be *overwritten*
    - Sensitive: MyData is *not the same* as mydata

